language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add rustfmt

script:
  - ci/script.sh
  - cargo fmt -- --check

matrix:
  exclude:
    - rust: nightly
  include:
    - rust: nightly
      env: FEATURES=nightly
